### PR TITLE
third generation PCB

### PR DESCRIPTION
**Pull request by antoinealb**
Opening this to track the review comments.

Main changes:

* USB-C connector, its 2021
* Added footprints for JST XH connectors, for other teams that wish for an easier to handle connector.
* Designed for automated pick and place (almost all components on one side)
* Added a pinout for SWD output: I would like to try to port [BlackMagic probe](https://github.com/blacksphere/blackmagic) on this.
* Changed some components that are not in stock anymore.

@nuft can you review this if you have time?

### CODE REVIEW

**Comment by msplr** [comment]
Overall, the schematic is really tidy now. I still have a few comments/questions:

1) Is there a particular reason for changing the CAN transceiver (the selected component is fine though, just wondering)
2) I think UART RX/TX should be swapped on the SWD output (for black magic probe) because it is debugger side. (unless you want to cross the cable)
3) The status LEDs should have a properly sized for the selected LED.

For the PCB layout I'm not finished reviewing but here are some remarks:

1) Replace LED references D1-D3 with labels describing the function.
2) I think placing the button on the opposite side of the USB connector makes it easier to press it when plugging, while holding the PCB at the connector. What do you think?
3) The silk screen component references have varying text sizes. Maybe make it the same for nicer aesthetics.

This is really a great improvement! Thanks @antoinealb

**Comment by antoinealb** [comment]
> Is there a particular reason for changing the CAN transceiver (the selected component is fine though, just wondering)

I changed for one that is available as a common component in LCSC/JLCPCB, so that they can assemble it for us.

> I think UART RX/TX should be swapped on the SWD output (for black magic probe) because it is debugger side. (unless you want to cross the cable)

Thats correct, doing it now.

> The status LEDs should have a properly sized for the selected LED.

I guess you mean properly selected resistor ? I think the values I selected should be fine based on the datasheet (~100Ohm for each), but do you have a concern with this ?

> Replace LED references D1-D3 with labels describing the function.

Done

> I think placing the button on the opposite side of the USB connector makes it easier to press it when plugging, while holding the PCB at the connector. What do you think?

Its what we have on the current one, correct? I'd rather have the button on the top layer, so it gets assembled automatically. I made a small cardboard mockup of the PCB, and I think it should be fine for flashing.

> The silk screen component references have varying text sizes. Maybe make it the same for nicer aesthetics.

Done

> This is really a great improvement! Thanks @antoinealb

Thank you :)

**Comment by msplr** [comment]
> I guess you mean properly selected resistor ? I think the values I selected should be fine based on the datasheet (~100Ohm for each), but do you have a concern with this ?

Yes, the word "resistor" got lost during editing.
I think it's nicer if the brightness is matched such that they are equally visible.

> Its what we have on the current one, correct? I'd rather have the button on the top layer, so it gets assembled automatically. I made a small cardboard mockup of the PCB, and I think it should be fine for flashing.

You're right, one doesn't flash the firmware so often.


About the black magic probe UART: You could use UART2 for this (PA2/PA3 or PB3/PB4) such that it doesn't conflict with the debug UART1.

**Comment by antoinealb** [comment]
> About the black magic probe UART: You could use UART2 for this (PA2/PA3 or PB3/PB4) such that it doesn't conflict with the debug UART1.

Done

**Pull request merged**
